version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3.8.5-management"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./queue/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
      - ./queue/definitions.json:/etc/rabbitmq/definitions.json:ro
  producer:
    build: ./producer
    depends_on:
      - rabbitmq
  consumer:
    build: ./consumer
    command: python consumer.py
    depends_on:
      - rabbitmq
  reprocess:
    build: ./reprocess
    command: python reprocess.py
    depends_on:
      - rabbitmq