apiVersion: 1

datasources:
  - name: 'Prometheus'
    type: 'prometheus'
    access: 'proxy'
    url: 'prometheus:9090'
    basicAuth: false
    isDefault: true
    jsonData:
      timeInterval: '5s'